flowchart TD

    %% ========= TABLES ========= %%

    USERS["USERS
    -----------------------
    id PK
    email
    password
    pseudo
    avatar (BYTEA)
    banner
    emblem
    trophy
    nbgame
    nbwin
    nblose
    nbdraw
    bio
    joined_at
    role
    is_active
    nbreport
    is_banned
    ban_reason
    last_seen
    reset_password_token
    reset_password_expires
    ban_label
    banned_until
    "]


    PUZZLES["PUZZLES
    -----------------------
    id PK
    fen
    solution (JSONB)
    elo
    themes (TEXT[])
    "]


    MATCHES["MATCHES
    -----------------------
    id PK
    mode
    finished_at
    state (JSONB)
    "]


    MATCH_PLAYERS["MATCH_PLAYERS
    -----------------------
    id PK
    match_id FK
    user_id FK
    is_winner
    puzzles_solved
    trophies_delta
    "]


    FRIENDS["FRIENDS
    -----------------------
    id PK
    requester_id FK
    receiver_id FK
    status
    created_at
    "]


    CHALLENGES["CHALLENGES
    -----------------------
    id PK
    from_user_id FK
    to_user_id FK
    status
    created_at
    "]


    REPORTS["REPORTS
    -----------------------
    id PK
    reporter_id FK
    reported_id FK
    reason
    created_at
    status
    "]


    %% ========= RELATIONS ========= %%

    %% USERS - FRIENDS
    USERS -- "1 .. n\n(requests)" --> FRIENDS
    USERS -- "1 .. n\n(receives)" --> FRIENDS

    %% USERS - CHALLENGES
    USERS -- "1 .. n\n(sent)" --> CHALLENGES
    USERS -- "1 .. n\n(received)" --> CHALLENGES

    %% USERS - REPORTS
    USERS -- "1 .. n\n(reporter)" --> REPORTS
    USERS -- "1 .. n\n(reported)" --> REPORTS

    %% MATCHES - MATCH_PLAYERS
    MATCHES -- "1 .. n" --> MATCH_PLAYERS

    %% USERS - MATCH_PLAYERS
    USERS -- "1 .. n" --> MATCH_PLAYERS

    %% PUZZLES : aucune relation externe
